import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import {
  CallToolRequestSchema,
  ListResourcesRequestSchema,
  ListToolsRequestSchema,
  ReadResourceRequestSchema,
} from "@modelcontextprotocol/sdk/types.js";
import { BrowserManager } from "./BrowserManager.js";
import fs from "node:fs";
import path from "node:path";
import { discordNotifier } from "./DiscordWebhook.js";

const browser = new BrowserManager();

const server = new Server(
  {
    name: "splice-enterprise-browser",
    version: "2.0.0",
  },
  {
    capabilities: {
      resources: {},
      tools: {},
    },
  }
);

// Define Resources
server.setRequestHandler(ListResourcesRequestSchema, async () => {
  return {
    resources: [
      {
        uri: "splice://current-page/semantic-tree",
        name: "Semantic Tree (Raw)",
        mimeType: "application/json",
        description: "The full, raw AI-optimized semantic representation of the current page's DOM structure.",
      },
      {
        uri: "splice://current-page/telemetry",
        name: "Telemetry Data",
        mimeType: "application/json",
        description: "Network and console logs generated by the page.",
      },
      {
        uri: "splice://session/health-dashboard",
        name: "Health & Performance Dashboard",
        mimeType: "application/json",
        description: "Tracks tokens saved, errors prevented, and CAPTCHAs handled in this session.",
      },
      {
        uri: "splice://session/live-feed",
        name: "Live Heartbeat Feed",
        mimeType: "application/json",
        description: "A real-time rolling window of the last 5 agent actions and 5 console logs — the agent's heartbeat.",
      }
    ],
  };
});

server.setRequestHandler(ReadResourceRequestSchema, async (request) => {
  if (request.params.uri === "splice://current-page/semantic-tree") {
    try {
      const tree = await browser.getSemanticTree();
      return {
        contents: [
          {
            uri: request.params.uri,
            mimeType: "application/json",
            text: JSON.stringify(tree, null, 2),
          },
        ],
      };
    } catch (e: any) {
      return {
        contents: [
          {
            uri: request.params.uri,
            mimeType: "application/json",
            text: JSON.stringify({ error: e.message }),
          },
        ],
      };
    }
  }

  if (request.params.uri === "splice://current-page/telemetry") {
    try {
      const logs = browser.getTelemetryLogs();
      return {
        contents: [
          {
            uri: request.params.uri,
            mimeType: "application/json",
            text: JSON.stringify(logs, null, 2),
          },
        ],
      };
    } catch (e: any) {
      return {
        contents: [
          {
            uri: request.params.uri,
            mimeType: "application/json",
            text: JSON.stringify({ error: e.message }),
          },
        ],
      };
    }
  }

  if (request.params.uri === "splice://session/health-dashboard") {
    return {
      contents: [{ uri: request.params.uri, mimeType: "application/json", text: JSON.stringify(browser.metrics, null, 2) }],
    };
  }

  if (request.params.uri === "splice://session/live-feed") {
    return {
      contents: [{ uri: request.params.uri, mimeType: "application/json", text: JSON.stringify(browser.getLiveFeed(), null, 2) }],
    };
  }

  throw new Error(`Resource not found: ${request.params.uri}`);
});

// Define Tools
server.setRequestHandler(ListToolsRequestSchema, async () => {
  return {
    tools: [
      {
        name: "navigate",
        description: "Navigate the active browser branch to a specific URL.",
        inputSchema: {
          type: "object",
          properties: {
            url: { type: "string", description: "The full URL to navigate to" },
          },
          required: ["url"],
        },
      },
      {
        name: "get_semantic_tree_optimized",
        description: "Extract the Semantic Tree using a specialized lens (UX, Security, Performance) and intent pruning.",
        inputSchema: {
          type: "object",
          properties: {
            intent: { type: "string", description: "Your current goal (e.g. 'checkout', 'login', 'read article'). Used to prune irrelevant DOM elements." },
            lens: { type: "string", enum: ["UX", "Security", "Performance", "Vision"], description: "The Semantic Lens to view the page through." },
            maxTokens: { type: "number", description: "The maximum number of tokens to return. Triggers aggressive truncation if exceeded." }
          },
          required: ["intent"],
        },
      },
      {
        name: "interact",
        description: "Interact with an element using its splice ID (found in the semantic tree). Also handles conflict resolution between agents.",
        inputSchema: {
          type: "object",
          properties: {
            elementId: { type: "string", description: "The data-splice-id of the element (e.g., 'button-1')" },
            action: { type: "string", enum: ["click", "type", "focus", "select", "press"], description: "The action to perform" },
            value: { type: "string", description: "Optional value for 'type', 'select', or 'press' actions" },
            agentId: { type: "string", description: "Optional agent identifier to track conflicts." }
          },
          required: ["elementId", "action"],
        },
      },
      {
        name: "diagnose_agent_state",
        description: "Agent State Forensics: classify why the current browser workflow is ready, stuck, obstructed, blocked by validation, waiting on auth, or failing due to network/CAPTCHA state.",
        inputSchema: {
          type: "object",
          properties: {
            goal: { type: "string", description: "Optional current agent goal, used to make the diagnosis more specific." },
            lastActions: {
              type: "array",
              items: { type: "string" },
              description: "Optional recent action summaries, newest last."
            }
          }
        },
      },
      {
        name: "compile_verified_action",
        description: "Verified Intent Actions: compile a natural-language browser intent into a target, preconditions, postconditions, risk score, alternatives, and optional execution with verification.",
        inputSchema: {
          type: "object",
          properties: {
            intent: { type: "string", description: "The browser intent, e.g. 'click the pricing link' or 'fill email field'." },
            value: { type: "string", description: "Optional value for type/select/press actions." },
            execute: { type: "boolean", description: "If true, execute only when confidence and preconditions are sufficient." },
            constraints: {
              type: "object",
              properties: {
                noNavigationOutsideDomain: { type: "boolean", description: "Penalize or reject targets that navigate to a different host." },
                avoidDestructiveActions: { type: "boolean", description: "Block destructive intents such as delete, pay, buy, transfer, or cancellation." },
                requireExactText: { type: "boolean", description: "Require candidate labels to include intent terms." }
              }
            }
          },
          required: ["intent"],
        },
      },
      {
        name: "fork_state",
        description: "Clone the current browser state into a new background branch for shadow testing risky actions.",
        inputSchema: {
          type: "object",
          properties: {
            agentId: { type: "string", description: "Optional agent ID that will own the new branch. Ownership is recorded immediately." }
          },
        },
      },
      {
        name: "speculative_fork",
        description: "Proactively fork branches and navigate to a list of URLs in the background to reduce latency when you later navigate to them.",
        inputSchema: {
          type: "object",
          properties: {
            urls: {
              type: "array",
              items: { type: "string" },
              description: "Array of URLs to speculatively pre-load."
            }
          },
          required: ["urls"],
        },
      },
      {
        name: "commit_branch",
        description: "Make a background branch the primary active state.",
        inputSchema: {
          type: "object",
          properties: {
            branchId: { type: "string", description: "The branch ID to commit" },
          },
          required: ["branchId"],
        },
      },
      {
        name: "save_snapshot",
        description: "Serialize the active session (cookies, auth) to the local machine so it can be resumed instantly.",
        inputSchema: {
          type: "object",
          properties: {
            name: { type: "string", description: "Name of the snapshot (e.g., 'auth-github')" },
          },
          required: ["name"],
        },
      },
      {
        name: "load_snapshot",
        description: "Instantly teleport the browser into a previously saved session state.",
        inputSchema: {
          type: "object",
          properties: {
            name: { type: "string", description: "Name of the snapshot to load" },
          },
          required: ["name"],
        },
      },
      {
        name: "request_human_intervention",
        description: "Halt the agent and spawn a visible Chromium window on the host machine to solve a CAPTCHA or unblock a flow.",
        inputSchema: {
          type: "object",
          properties: {
            reason: { type: "string", description: "Why the human is needed (e.g., 'Solve Cloudflare turnstile')" },
          },
          required: ["reason"],
        },
      },
      {
        name: "debug_failure",
        description: "Save a time-travel Playwright trace of the current session to debug hallucination or errors.",
        inputSchema: {
          type: "object",
          properties: {
            sessionId: { type: "string", description: "A unique identifier for this debug trace" },
          },
          required: ["sessionId"],
        },
      },
      {
        name: "capture_node_screenshot",
        description: "Vision Lens: Capture a base64 encoded screenshot of a specific element to pass to a vision model.",
        inputSchema: {
          type: "object",
          properties: {
            elementId: { type: "string", description: "The data-splice-id of the element to capture" },
          },
          required: ["elementId"],
        },
      },
      {
        name: "generate_observability_report",
        description: "Generate a high-aesthetic HTML dashboard with auto-refresh every 5s showing micro-snapshots and metrics.",
        inputSchema: { type: "object", properties: {} },
      },
      {
        name: "launch_command_center",
        description: "Start a localhost Command Center server for the latest observability dashboard and return a browser-friendly URL.",
        inputSchema: {
          type: "object",
          properties: {
            preferredPort: { type: "number", description: "Optional preferred localhost port. Defaults to 4821." },
          },
        },
      },
      {
        name: "capture_annotated_screenshot",
        description: "Vibe Coding: Capture a base64 screenshot where every interactive element has a bright bounding box and ID label.",
        inputSchema: { type: "object", properties: {} },
      },
      {
        name: "execute_script",
        description: "God-Mode: Execute arbitrary JavaScript in the browser context.",
        inputSchema: {
          type: "object",
          properties: {
            script: { type: "string", description: "JavaScript to execute. Must return a serializable value or undefined." },
          },
          required: ["script"],
        },
      },
      {
        name: "toggle_watch_mode",
        description: "Toggle between headless (invisible) and headful (visible) browser. When enabled, a real Chrome window appears so you can watch the agent work.",
        inputSchema: {
          type: "object",
          properties: {
            enabled: { type: "boolean", description: "true = visible browser, false = headless" },
          },
          required: ["enabled"],
        },
      },
      {
        name: "maintenance_cleanup",
        description: "Delete old snapshots, traces, and report files to free disk space.",
        inputSchema: {
          type: "object",
          properties: {
            olderThanDays: { type: "number", description: "Delete files older than this many days (default: 7)" },
          },
        },
      },
      {
        name: "run_security_audit",
        description: "Agent QA Lab: Run a comprehensive security audit against a URL. Checks security headers, XSS surfaces, CSRF tokens, sensitive data exposure, and third-party dependencies. Automatically crawls linked pages and returns a structured, machine-readable report with actionable AI feedback.",
        inputSchema: {
          type: "object",
          properties: {
            targetUrl: {
              type: "string",
              description: "The URL of the app to audit (e.g. http://localhost:3000)"
            },
            safeMode: {
              type: "boolean",
              description: "If true (default), skip active form probing. Set to false for full active XSS scanning in dev environments only."
            },
            crawl: {
              type: "boolean",
              description: "If true (default), automatically follow same-domain links and audit each page."
            },
            maxCrawlDepth: {
              type: "number",
              description: "Maximum number of pages to crawl (default: 5)."
            },
            checks: {
              type: "array",
              items: { type: "string", enum: ["headers", "xss", "auth", "data", "deps", "exploits", "openclaw"] },
              description: "Which checks to run. Defaults to all: headers, xss, auth, data, deps, exploits, openclaw."
            }
          },
          required: ["targetUrl"]
        }
      },
      {
        name: "run_diagnostics",
        description: "DX QoL: Run a health check on the Splice environment. Verifies Playwright, Chromium, Vault, and Network connectivity.",
        inputSchema: { type: "object", properties: {} },
      },
      {
        name: "toggle_resource_blocking",
        description: "Performance QoL: Toggle blocking of ads, tracking, and heavy media (images/video). Default is ON for agents.",
        inputSchema: {
          type: "object",
          properties: {
            enabled: { type: "boolean", description: "true = block ads/media, false = allow all" },
          },
          required: ["enabled"],
        },
      },
      {
        name: "get_product_intelligence",
        description: "Behavioral V4: Analyze user behavior logs (clicks, rage-clicks, friction) and provide product-driven feature recommendations for coding agents.",
        inputSchema: {
          type: "object",
          properties: {
            targetUrl: { type: "string", description: "The URL of the product to analyze." },
            intent: { type: "string", description: "Optional specific feature goal (e.g. 'Optimize checkout flow')." }
          },
          required: ["targetUrl"]
        },
      },
      {
        name: "scan_local_secrets",
        description: "Agentic Security V5: Scan the local workspace repository for hardcoded API keys or secrets to prevent supply chain leaks.",
        inputSchema: {
          type: "object",
          properties: {
            directory: { type: "string", description: "The directory to scan. Defaults to process.cwd()." }
          }
        }
      },
      {
        name: "toggle_openclaw_gateway",
        description: "Control the dynamic lifecycle of the optional local OpenClaw gateway server (port 18789). Enables/disables local OpenClaw agents from connecting.",
        inputSchema: {
          type: "object",
          properties: {
            enabled: { type: "boolean", description: "Set true to start the gateway, false to stop it." }
          },
          required: ["enabled"]
        }
      },
      {
        name: "configure_discord_webhook",
        description: "Dynamically configure or update the target Discord Webhook URL for automated significant-event notifications.",
        inputSchema: {
          type: "object",
          properties: {
            webhookUrl: { type: "string", description: "The full Discord webhook URL." }
          },
          required: ["webhookUrl"]
        }
      },
      {
        name: "send_discord_update",
        description: "Send a manual custom status or alert card directly to the configured Discord channel.",
        inputSchema: {
          type: "object",
          properties: {
            title: { type: "string", description: "Title of the alert card." },
            description: { type: "string", description: "Summary or message details." },
            color: { type: "string", enum: ["red", "green", "yellow", "blue"], description: "Color signature of the notification." }
          },
          required: ["title", "description"]
        }
      },
      // ─── Multi-Agent Collaboration Tools ──────────────────────────────────────
      {
        name: "register_agent",
        description: "Multi-Agent: Register this agent with Splice and declare its role. Enables role-appropriate constraints and branch ownership tracking. Roles: explorer, verifier, executor, auditor.",
        inputSchema: {
          type: "object",
          properties: {
            agentId: { type: "string", description: "Stable identifier for this agent instance (e.g. 'explorer-1')." },
            role: { type: "string", enum: ["explorer", "verifier", "executor", "auditor"], description: "The agent's functional role." }
          },
          required: ["agentId", "role"]
        }
      },
      {
        name: "get_canonical_context",
        description: "Multi-Agent: Pull the Canonical Context Snapshot (CCS) — the single shared source of truth that replaces all agent-to-agent messaging. Returns active branches, promoted findings, quorum state, and registered agents.",
        inputSchema: { type: "object", properties: {} }
      },
      {
        name: "acquire_branch_ownership",
        description: "Multi-Agent: Claim exclusive write access to a browser branch. Required before calling interact, promote_finding, or handoff_branch on that branch. Fails if another agent already holds it.",
        inputSchema: {
          type: "object",
          properties: {
            branchId: { type: "string", description: "The branch to acquire ownership of." },
            agentId: { type: "string", description: "The acquiring agent's ID." }
          },
          required: ["branchId", "agentId"]
        }
      },
      {
        name: "promote_finding",
        description: "Multi-Agent: Promote a locally-produced finding to the Immutable Evidence Ledger so other agents can read it via get_canonical_context. Requires a confidence score (0–1). Conflicting findings on the same key are flagged for quorum resolution rather than silently overwritten.",
        inputSchema: {
          type: "object",
          properties: {
            key: { type: "string", description: "Semantic topic key, e.g. 'auth.status' or 'checkout.form.valid'." },
            value: { description: "The finding value (any JSON-serializable type)." },
            confidence: { type: "number", description: "0–1. How confident the agent is in this finding. Entries below 0.7 are excluded from the CCS until resolved." },
            branchId: { type: "string", description: "The branch this finding was produced from. Agent must own this branch." },
            agentId: { type: "string", description: "The agent promoting the finding." }
          },
          required: ["key", "value", "confidence", "branchId", "agentId"]
        }
      },
      {
        name: "resolve_conflict",
        description: "Multi-Agent: Resolve a quorum conflict on a ledger key by selecting the highest-confidence entry. Marks losing entries as superseded and unblocks actions that were waiting on consensus.",
        inputSchema: {
          type: "object",
          properties: {
            key: { type: "string", description: "The conflicted ledger key to resolve." }
          },
          required: ["key"]
        }
      },
      {
        name: "handoff_branch",
        description: "Multi-Agent: Atomically transfer write ownership of a browser branch from one agent to another. The source agent must currently own the branch. The transfer is recorded in the ledger for auditability.",
        inputSchema: {
          type: "object",
          properties: {
            branchId: { type: "string", description: "The branch to transfer." },
            fromAgentId: { type: "string", description: "The agent releasing ownership." },
            toAgentId: { type: "string", description: "The agent receiving ownership." }
          },
          required: ["branchId", "fromAgentId", "toAgentId"]
        }
      },
      {
        name: "get_coordination_health",
        description: "Multi-Agent: Returns CoordinationTaxMetrics — a live measure of overhead introduced by multi-agent collaboration. Non-zero values in conflictsDetected, blockedActions, or ownershipViolationAttempts indicate the system is paying a coordination tax.",
        inputSchema: { type: "object", properties: {} }
      },
      {
        name: "get_summons",
        description: "Multi-Agent: List all pending and active summon requests from human users asking for help.",
        inputSchema: { type: "object", properties: {} }
      },
      {
        name: "acknowledge_summon",
        description: "Multi-Agent: Let an agent acknowledge a pending summon by ID, marking it as accepted by that agent.",
        inputSchema: {
          type: "object",
          properties: {
            summonId: { type: "string", description: "The ID of the summon to acknowledge (e.g., 'summon-123')." },
            agentId: { type: "string", description: "The ID of the agent acknowledging the summon." }
          },
          required: ["summonId", "agentId"]
        }
      }
    ],
  };
});

server.setRequestHandler(CallToolRequestSchema, async (request) => {
  try {
    if (request.params.name === "navigate") {
      const { url } = request.params.arguments as { url: string };
      await browser.navigate(url);
      return { content: [{ type: "text", text: `Navigated to ${url}.` }] };
    }

    if (request.params.name === "get_semantic_tree_optimized") {
      const { intent, lens, maxTokens } = request.params.arguments as any;
      const tree = await browser.getSemanticTree(intent, lens || "UX", maxTokens);
      return { content: [{ type: "text", text: JSON.stringify(tree, null, 2) }] };
    }

    if (request.params.name === "interact") {
      const { elementId, action, value, agentId } = request.params.arguments as any;
      await browser.interact(elementId, action, value, agentId);
      await new Promise(r => setTimeout(r, 1000)); // wait for network idle/renders
      return { content: [{ type: "text", text: `Successfully performed '${action}' on element '${elementId}'.` }] };
    }

    if (request.params.name === "diagnose_agent_state") {
      const { goal, lastActions } = (request.params.arguments as any) || {};
      const diagnosis = await browser.diagnoseAgentState(goal, Array.isArray(lastActions) ? lastActions : []);
      return { content: [{ type: "text", text: JSON.stringify(diagnosis, null, 2) }] };
    }

    if (request.params.name === "compile_verified_action") {
      const { intent, value, constraints, execute } = request.params.arguments as any;
      const plan = await browser.compileVerifiedAction({ intent, value, constraints, execute: execute === true });
      return { content: [{ type: "text", text: JSON.stringify(plan, null, 2) }] };
    }

    if (request.params.name === "fork_state") {
      const { agentId } = (request.params.arguments as any) || {};
      const branchId = await browser.forkState(agentId);
      return { content: [{ type: "text", text: `Created new branch: ${branchId}${agentId ? ` (owned by ${agentId})` : ''}. Switch using commit_branch.` }] };
    }

    if (request.params.name === "speculative_fork") {
      const { urls } = request.params.arguments as { urls: string[] };
      await browser.speculativeFork(urls);
      return { content: [{ type: "text", text: `Speculatively forked and pre-loaded ${urls.length} branches in the background.` }] };
    }

    if (request.params.name === "commit_branch") {
      const { branchId } = request.params.arguments as { branchId: string };
      await browser.commitBranch(branchId);
      return { content: [{ type: "text", text: `Active branch is now ${branchId}.` }] };
    }

    if (request.params.name === "save_snapshot") {
      const { name } = request.params.arguments as { name: string };
      const path = await browser.saveSnapshot(name);
      return { content: [{ type: "text", text: `Snapshot saved to ${path}.` }] };
    }

    if (request.params.name === "load_snapshot") {
      const { name } = request.params.arguments as { name: string };
      await browser.loadSnapshot(name);
      return { content: [{ type: "text", text: `Loaded snapshot ${name}. Session resumed.` }] };
    }

    if (request.params.name === "request_human_intervention") {
      const { reason } = request.params.arguments as { reason: string };
      await browser.requestHumanIntervention(reason);
      return { content: [{ type: "text", text: `Human solved the issue and returned control. Resume your task.` }] };
    }

    if (request.params.name === "debug_failure") {
      const { sessionId } = request.params.arguments as { sessionId: string };
      const tracePath = await browser.debugFailure(sessionId);
      return { content: [{ type: "text", text: `Saved Playwright trace to ${tracePath}. To view it, run 'npx playwright show-trace ${tracePath}' on the host machine.` }] };
    }

    if (request.params.name === "capture_node_screenshot") {
      const { elementId } = request.params.arguments as { elementId: string };
      const base64Str = await browser.captureNodeScreenshot(elementId);
      return { content: [{ type: "text", text: base64Str }] };
    }

    if (request.params.name === "generate_observability_report") {
      const reportPath = await browser.generateObservabilityReport();
      return { content: [{ type: "text", text: `Observability Dashboard generated at: ${reportPath}. Open this file in your browser to visualize the agent's processes.` }] };
    }

    if (request.params.name === "launch_command_center") {
      const { preferredPort } = (request.params.arguments as { preferredPort?: number }) || {};
      const launch = await browser.launchCommandCenter(preferredPort);
      return { content: [{ type: "text", text: `Command Center is running at ${launch.url} (report: ${launch.reportPath}).` }] };
    }

    if (request.params.name === "capture_annotated_screenshot") {
      const base64Str = await browser.captureAnnotatedScreenshot();
      return { content: [{ type: "text", text: base64Str }] };
    }

    if (request.params.name === "execute_script") {
      const { script } = request.params.arguments as { script: string };
      const result = await browser.executeScript(script);
      return { content: [{ type: "text", text: JSON.stringify(result, null, 2) }] };
    }

    if (request.params.name === "toggle_watch_mode") {
      const { enabled } = request.params.arguments as { enabled: boolean };
      await browser.toggleWatchMode(enabled);
      return { content: [{ type: "text", text: `Watch Mode is now ${enabled ? 'ENABLED — a browser window should be visible on your screen.' : 'DISABLED — running headless.'}` }] };
    }

    if (request.params.name === "maintenance_cleanup") {
      const { olderThanDays } = (request.params.arguments as any) || {};
      const result = await browser.maintenanceCleanup(olderThanDays ?? 7);
      return { content: [{ type: "text", text: `Cleanup complete. Removed ${result.removed} files older than ${result.olderThanDays} days.` }] };
    }

    if (request.params.name === "run_security_audit") {
      const { targetUrl, safeMode, crawl, maxCrawlDepth, checks } = request.params.arguments as any;
      const report = await browser.runSecurityAudit(targetUrl, {
        safeMode: safeMode !== false, // default true
        crawl: crawl !== false,       // default true
        maxCrawlDepth: maxCrawlDepth ?? 5,
        checks
      });

      // Return the agent-facing feedback as the primary response, with full JSON appended
      const agentText = [
        `=== SPLICE SECURITY AUDIT REPORT ===`,
        `Target: ${report.url}`,
        `Crawled: ${report.crawledUrls.length} page(s): ${report.crawledUrls.join(', ')}`,
        `Safe Mode: ${report.safeMode}`,
        ``,
        `SUMMARY: ${report.agentFeedback.summary}`,
        `Results: ${report.totals.critical} critical | ${report.totals.warning} warnings | ${report.totals.info} info | ${report.totals.passed} passed`,
        ``,
        report.agentFeedback.criticalActions.length > 0 ? `CRITICAL — FIX IMMEDIATELY:\n${report.agentFeedback.criticalActions.join('\n')}` : '',
        report.agentFeedback.warningActions.length > 0  ? `\nWARNINGS — ADDRESS BEFORE LAUNCH:\n${report.agentFeedback.warningActions.join('\n')}` : '',
        `\nPASSED CHECKS:\n${report.agentFeedback.passed.join('\n')}`,
        ``,
        `=== FULL JSON REPORT ===`,
        JSON.stringify(report, null, 2)
      ].filter(Boolean).join('\n');

      return { content: [{ type: "text", text: agentText }] };
    }

    if (request.params.name === "run_diagnostics") {
      const results = {
        playwright: "OK",
        chromium: "OK",
        vault: "OK",
        network: "OK",
        timestamp: new Date().toISOString()
      };
      // Simple connectivity check
      try { await browser.navigate("https://example.com"); } catch { results.network = "FAIL"; }
      
      return { content: [{ type: "text", text: `Splice Health Check:\n${JSON.stringify(results, null, 2)}` }] };
    }

    if (request.params.name === "toggle_resource_blocking") {
      const { enabled } = request.params.arguments as { enabled: boolean };
      await browser.toggleResourceBlocking(enabled);
      return { content: [{ type: "text", text: `Resource blocking is now ${enabled ? 'ENABLED' : 'DISABLED'}. Heavy media and ads will be ${enabled ? 'blocked' : 'allowed'} in new branches.` }] };
    }

    if (request.params.name === "get_product_intelligence") {
      const { targetUrl, intent } = request.params.arguments as { targetUrl: string, intent?: string };
      
      // 1. Get the behavior-focused semantic tree
      const tree = await browser.getSemanticTree(intent || "Analyze user behavior", "Behavior");
      
      // 2. Generate a high-level summary of hotspots and friction
      let frictionPoints: any[] = [];
      const findFriction = (node: any) => {
        if (node.behaviorSummary) {
          if (node.behaviorSummary.frictionScore > 30 || node.behaviorSummary.abandonedInputs > 0) {
            frictionPoints.push({
              element: node.text || node.type,
              id: node.id,
              clicks: node.behaviorSummary.clicks,
              rage: node.behaviorSummary.rageClicks,
              abandoned: node.behaviorSummary.abandonedInputs,
              score: node.behaviorSummary.frictionScore,
              scroll: node.behaviorSummary.maxScrollDepth
            });
          }
        }
        if (node.children) node.children.forEach(findFriction);
      };
      findFriction(tree);

      const maxScroll = frictionPoints.length > 0 ? frictionPoints[0].scroll : 0;

      const recommendations = frictionPoints.map(f => {
        if (f.abandoned > 0) return `- Input "${f.element}" (ID: ${f.id}) has high abandonment. Users start but don't finish. Suggest checking validation or label clarity.`;
        if (f.rage > 0) return `- Element "${f.element}" (ID: ${f.id}) is causing rage clicks. Suggest verifying if the event handler is responsive or if the UI is confusing.`;
        if (f.clicks > 10) return `- Element "${f.element}" (ID: ${f.id}) is a high-traffic hotspot. Suggest prioritizing feature enhancements here.`;
        return `- Element "${f.element}" has a friction score of ${f.score}. Suggest UI polish.`;
      }).join('\n');

      const scrollIntel = maxScroll < 50 ? `⚠️ Low engagement: Users only scroll to ${maxScroll}% of the page. Consider moving key content higher.` : `✅ Healthy engagement: Users scroll to ${maxScroll}% of the page.`;

      const intelReport = `
### 📊 Splice Deep Product Intelligence: ${targetUrl}

#### 🛠️ Behavioral Analysis
- Analyzed User Intent: ${intent || "General Exploration"}
- Friction Points Detected: ${frictionPoints.length}
- **Engagement (Scroll Depth):** ${scrollIntel}

#### 💡 Agent Recommendations
${recommendations || "- No major friction points detected. The current UI appears intuitive."}

#### 🤖 Action Plan for Coding Agent:
1. Optimize elements with high abandonment or rage-clicks.
2. Ensure primary CTAs are within the active scroll depth (${maxScroll}%).
3. Review the Behavioral Heatmap for visibility-dwell correlations.
      `.trim();

      return { content: [{ type: "text", text: intelReport }] };
    }

    if (request.params.name === "scan_local_secrets") {
      const { directory = process.cwd() } = (request.params.arguments as any) || {};
      const results: string[] = [];
      const SECRET_RX = /(AKIA[0-9A-Z]{16}|sk_(live|test)_[a-zA-Z0-9]{20,}|AIza[0-9A-Za-z\-_]{35}|eyJ[a-zA-Z0-9_\-]+\.[a-zA-Z0-9_\-]+\.[a-zA-Z0-9_\-]+)/;

      const scanDir = (dir: string) => {
        if (!fs.existsSync(dir)) return;
        const files = fs.readdirSync(dir);
        for (const file of files) {
          if (file === 'node_modules' || file === '.git' || file === '.splice' || file === 'dist') continue;
          const fullPath = path.join(dir, file);
          const stat = fs.statSync(fullPath);
          if (stat.isDirectory()) {
            scanDir(fullPath);
          } else {
            try {
              const content = fs.readFileSync(fullPath, 'utf8');
              const match = content.match(SECRET_RX);
              if (match) {
                results.push(`[EXPOSED SECRET] File: ${fullPath} contains potential secret: ${match[0].substring(0, 10)}...`);
              }
            } catch (e) { /* ignore binary/unreadable files */ }
          }
        }
      };

      scanDir(directory);
      const text = results.length > 0 
        ? `⚠️ WARNING: Found ${results.length} exposed secrets in the repository:\n${results.join('\n')}\nPlease remove these before committing!`
        : `✅ SCAN PASSED: No exposed API keys or secrets found in ${directory}.`;
      
      // Send automated Discord notification for exposed secrets
      if (results.length > 0 && discordNotifier.isActive()) {
        discordNotifier.sendEmbed({
          title: "🚨 CRITICAL: Exposed Secrets Found in Repository",
          description: `Splice local secret scanner has detected **${results.length}** exposed API keys or tokens in the codebase.`,
          color: 0xe74c3c,
          fields: [
            { name: "Scanned Directory", value: directory, inline: false },
            { name: "Details", value: results.join('\n').substring(0, 1000), inline: false }
          ],
          footerText: "Splice Enterprise Security Hub"
        }).catch(err => console.error("Error sending secrets alert to Discord:", err.message));
      }
      
      return { content: [{ type: "text", text }] };
    }

    if (request.params.name === "toggle_openclaw_gateway") {
      const { enabled } = request.params.arguments as { enabled: boolean };
      await browser.toggleOpenClawGateway(enabled);
      return { content: [{ type: "text", text: `OpenClaw Gateway server is now ${enabled ? 'ENABLED and listening securely on port 18789' : 'DISABLED'}.` }] };
    }

    if (request.params.name === "configure_discord_webhook") {
      const { webhookUrl } = request.params.arguments as { webhookUrl: string };
      discordNotifier.setWebhookUrl(webhookUrl);
      return { content: [{ type: "text", text: `Discord Webhook URL has been configured successfully.` }] };
    }

    if (request.params.name === "send_discord_update") {
      const { title, description, color } = request.params.arguments as { title: string; description: string; color?: string };
      
      let colorCode = 0x3498db; // blue
      if (color === "red") colorCode = 0xe74c3c;
      else if (color === "green") colorCode = 0x2ecc71;
      else if (color === "yellow") colorCode = 0xf1c40f;

      const sent = await discordNotifier.sendEmbed({
        title,
        description,
        color: colorCode
      });

      if (!sent) {
        return { 
          content: [{ type: "text", text: `Failed to send Discord update. Ensure DISCORD_WEBHOOK_URL is configured.` }],
          isError: true
        };
      }
      return { content: [{ type: "text", text: `Successfully sent manual status update to Discord.` }] };
    }

    // ─── Multi-Agent Collaboration Handlers ─────────────────────────────────

    if (request.params.name === "register_agent") {
      const { agentId, role } = request.params.arguments as { agentId: string; role: any };
      const reg = browser.coordinator.registerAgent(agentId, role);
      return { content: [{ type: "text", text: `Agent registered:\n${JSON.stringify(reg, null, 2)}` }] };
    }

    if (request.params.name === "get_canonical_context") {
      const ccs = browser.coordinator.buildCanonicalContext();
      return { content: [{ type: "text", text: JSON.stringify(ccs, null, 2) }] };
    }

    if (request.params.name === "acquire_branch_ownership") {
      const { branchId, agentId } = request.params.arguments as { branchId: string; agentId: string };
      const acquired = browser.coordinator.acquireOwnership(branchId, agentId);
      if (!acquired) {
        const owner = browser.coordinator.getOwner(branchId);
        return {
          content: [{ type: "text", text: `Ownership rejected: branch "${branchId}" is currently owned by "${owner}". Call handoff_branch first, or wait for the owner to release it.` }],
          isError: true
        };
      }
      return { content: [{ type: "text", text: `Agent "${agentId}" now owns branch "${branchId}". You may now call interact and promote_finding on this branch.` }] };
    }

    if (request.params.name === "promote_finding") {
      const { key, value, confidence, branchId, agentId } = request.params.arguments as any;
      const entry = browser.promoteFinding(key, value, confidence, branchId, agentId);
      const conflicted = browser.coordinator.getConflictedKeys();
      const isConflicted = conflicted.includes(key);
      return {
        content: [{
          type: "text",
          text: [
            `Finding promoted to ledger (id=${entry.id}).`,
            isConflicted
              ? `⚠️  CONFLICT DETECTED on key "${key}": another agent has posted a contradictory finding. Call resolve_conflict to unblock related actions.`
              : `✅ No conflicts on key "${key}". Finding is visible in the Canonical Context.`
          ].join('\n')
        }]
      };
    }

    if (request.params.name === "resolve_conflict") {
      const { key } = request.params.arguments as { key: string };
      const winner = browser.coordinator.resolveConflict(key);
      if (!winner) {
        return { content: [{ type: "text", text: `No active conflict found for key "${key}".` }] };
      }
      return {
        content: [{
          type: "text",
          text: [
            `Conflict resolved for key "${key}".`,
            `Winner: agent "${winner.agentId}" (confidence=${winner.confidence}, id=${winner.id}).`,
            `Any actions that were blocked by this conflict are now unblocked.`
          ].join('\n')
        }]
      };
    }

    if (request.params.name === "handoff_branch") {
      const { branchId, fromAgentId, toAgentId } = request.params.arguments as any;
      browser.handoffBranch(branchId, fromAgentId, toAgentId);
      return { content: [{ type: "text", text: `Branch "${branchId}" transferred from "${fromAgentId}" to "${toAgentId}". Transfer recorded in the Evidence Ledger.` }] };
    }

    if (request.params.name === "get_coordination_health") {
      const metrics = browser.coordinator.getCoordinationTaxMetrics();
      const ccs = browser.coordinator.buildCanonicalContext();
      const report = [
        `=== COORDINATION HEALTH REPORT ===`,
        `System State: ${ccs.systemState.toUpperCase()}`,
        ``,
        `COORDINATION TAX METRICS (non-zero = overhead introduced by multi-agent setup):`,
        `  Conflicts Detected:           ${metrics.conflictsDetected}`,
        `  Conflicts Resolved:           ${metrics.conflictsResolved}`,
        `  Actions Blocked by Quorum:    ${metrics.blockedActions}`,
        `  Ownership Violation Attempts: ${metrics.ownershipViolationAttempts}`,
        `  Forced Branch Releases:       ${metrics.forcedReleases}`,
        ``,
        `CONFLICTED KEYS (require resolve_conflict):`,
        ccs.blockedKeys.length > 0 ? ccs.blockedKeys.map(k => `  - ${k}`).join('\n') : '  None',
        ``,
        `REGISTERED AGENTS: ${ccs.registeredAgents.length}`,
        ...ccs.registeredAgents.map(a => `  - ${a.agentId} [${a.role}]`),
        ``,
        `ACTIVE BRANCHES: ${ccs.activeBranches.length}`,
        ...ccs.activeBranches.map(b => `  - ${b.branchId} → owner: ${b.ownerAgentId ?? 'none'} (${b.currentUrl})`),
      ].join('\n');
      return { content: [{ type: "text", text: report }] };
    }

    if (request.params.name === "get_summons") {
      const summons = browser.coordinator.getSummons();
      return { content: [{ type: "text", text: JSON.stringify(summons, null, 2) }] };
    }

    if (request.params.name === "acknowledge_summon") {
      const { summonId, agentId } = request.params.arguments as { summonId: string; agentId: string };
      const req = browser.acknowledgeSummon(summonId, agentId);
      if (!req) {
        return {
          content: [{ type: "text", text: `Summon request with ID "${summonId}" not found.` }],
          isError: true
        };
      }
      return { content: [{ type: "text", text: `Agent "${agentId}" successfully acknowledged summon "${summonId}". You are now assigned to help the user on branch 'main'.` }] };
    }

    throw new Error(`Tool not found: ${request.params.name}`);
  } catch (error: any) {
    if (error.message.includes("CAPTCHA_REQUIRED")) {
       return {
         content: [{ type: "text", text: "ERROR: CAPTCHA detected. Please call the 'request_human_intervention' tool." }],
         isError: true,
       };
    }
    return {
      content: [{ type: "text", text: `Error executing tool: ${error.message}` }],
      isError: true,
    };
  }
});

async function main() {
  await browser.init();
  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error("Splice Enterprise MCP Server is running...");
}

main().catch((error) => {
  console.error("Fatal error running server:", error);
  process.exit(1);
});
